# Generated by Django 6.0.1 on 2026-02-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_documentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="documentos",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("200", "depósito (200)"),
                    ("203", "exame (203)"),
                    ("207", "cumprimento exigência (207)"),
                    ("260", "outras petições (260)"),
                    ("281", "manifestação (281)"),
                    ("9.2", "Indeferimento (9.2)"),
                    ("214", "recurso (214)"),
                    ("121", "exigências (121)"),
                    ("280", "cumprimento exigência (280)"),
                    ("111", "recurso negado (111)"),
                    ("100.1", "recurso provido (100.1)"),
                    (
                        "100.2",
                        "recurso provido com retorno à primeira instância (100.2)",
                    ),
                    ("130", "recurso prejudicado (130)"),
                ],
                default="O",
                max_length=255,
            ),
        ),
    ]
