# Generated by Django 6.0.1 on 2026-02-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_cliente_numero_alter_documentos_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentos",
            name="codigo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentos",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("6.1", "exigência (6.1)"),
                    ("7.1", "ciência de parecer (7.1)"),
                    ("200", "depósito (200)"),
                    ("203", "exame (203)"),
                    ("207", "cumprimento exigência (207)"),
                    ("260", "outras petições (260)"),
                    ("281", "manifestação (281)"),
                    ("9.2", "indeferimento (9.2)"),
                    ("214", "recurso (214)"),
                    ("121", "recurso exigência (121)"),
                    ("280", "cumprimento exigência (280)"),
                    ("111", "recurso negado (111)"),
                    ("100.1", "recurso provido-reforma (100.1)"),
                    ("100.2", "recurso provido-devolução (100.2)"),
                    ("130", "recurso prejudicado (130)"),
                ],
                default="O",
                max_length=255,
            ),
        ),
    ]
