# Generated by Django 6.0.1 on 2026-02-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_documentos_codigo_alter_documentos_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentos",
            name="numnossonumero",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="documentos",
            name="peticao",
            field=models.CharField(default="", max_length=255),
        ),
    ]
