# Generated by Django 6.0.1 on 2026-02-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_documentos_numnossonumero_documentos_peticao"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentos",
            name="documento_pdf",
            field=models.CharField(default="", max_length=255),
        ),
    ]
