# Generated by Django 6.0.1 on 2026-02-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_analisejurisprudencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisejurisprudencia',
            old_name='problemas_formatacao',
            new_name='resumo_pedido',
        ),
    ]
