# Generated by Django 6.0.1 on 2026-02-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ia", "0004_rename_problemas_formatacao_analisejurisprudencia_resumo_pedido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analisejurisprudencia",
            old_name="riscos_juridicos",
            new_name="historico_pedido",
        ),
    ]
