# Generated by Django 6.0.1 on 2026-02-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia", "0005_rename_riscos_juridicos_analisejurisprudencia_historico_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisejurisprudencia",
            name="comparacao_docs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="analisejurisprudencia",
            name="resumo_recurso",
            field=models.JSONField(default=list),
        ),
    ]
